//! Shared types and helpers for the Axum HTTP server.
//!
//! These live in the library crate (behind `#[cfg(feature = "server")]`)
//! so that code generated by `#[derive_handlers]` can reference them.

use std::sync::Arc;

use axum::http::StatusCode;
use axum::Json;
use serde_json::Value;
use tokio::sync::broadcast;

use crate::state::AppState;

/// Shared server state, wrapping the core `AppState` with a WebSocket broadcast channel.
pub struct ServerState {
    pub app: Arc<AppState>,
    pub ws_tx: broadcast::Sender<String>,
}

/// Serialize a value to `Json<Value>`, mapping serialization failure to
/// `INTERNAL_SERVER_ERROR`.
pub fn ok_json<T: serde::Serialize>(v: T) -> Result<Json<Value>, (StatusCode, String)> {
    Ok(Json(serde_json::to_value(v).map_err(|e| {
        (StatusCode::INTERNAL_SERVER_ERROR, e.to_string())
    })?))
}

/// Parse a UUID string, returning `BAD_REQUEST` on failure.
pub fn parse_uuid(s: &str) -> Result<uuid::Uuid, (StatusCode, String)> {
    uuid::Uuid::parse_str(s).map_err(|e| (StatusCode::BAD_REQUEST, e.to_string()))
}
